import type { SiteDefinition } from './src/lib/site-types';

const site = {
  network: { version: 1, sites: [] },
  consent: {
    cookieName: 'site_consent', revision: 1, retentionDays: 180,
    ui: {
      settings: 'Personvernvalg', title: 'Vil du at vi skal måle besøket?',
      description: 'Husutstyr.no måler ingenting før du sier ja. Sier du ja, teller vi sidevisninger, hvor raskt sidene laster, og hvilke annonselenker som blir klikket. Svaret ditt lagres i 180 dager, og du kan snu når som helst under Personvernvalg nederst.',
      accept: 'Godta analyse', reject: 'Avvis analyse', customize: 'Tilpass valg', save: 'Lagre mine valg', close: 'Lukk personvernvalg',
      necessary: 'Nødvendig lagring', necessaryDescription: 'Én informasjonskapsel husker hva du svarte og hvilken versjon av policyen du tok stilling til. Den settes uansett hva du velger, ellers ville vi spurt deg på nytt hver gang. Den måler ingenting.',
      analytics: 'Besøksanalyse og teknisk ytelse', analyticsDescription: 'Vi bruker Vercel Web Analytics og Speed Insights. De registrerer hvilke sider som åpnes, hvor raskt de laster, og hvilken annonselenke som ble klikket. Om klikket lagres lenke-ID, artikkel-ID, plassering og butikkens domene, men verken full produktadresse eller søkeparametre.',
      revision: 'Samtykkepolicyen er endret. Velg på nytt.', policyLink: '<a href="/personvern">Personvern</a> · <a href="/cookies">Informasjonskapsler</a>',
    },
  },
  measurement: {
    enabled: true,
    analyticsScript: '/_vercel/insights/script.js', analyticsEndpoint: '/_vercel/insights',
    speedScript: '/_vercel/speed-insights/script.js', speedEndpoint: '/_vercel/speed-insights/vitals',
    excludedPaths: ['/api', '/redaksjon', '/go', '/og', '/visninger', '/sider'],
    eventName: 'affiliate_click',
  },
  affiliate: { allowedOrigins: [], disclosure: 'Reklame: Noen lenker på denne siden er annonselenker. Handler du gjennom dem, kan Husutstyr.no få provisjon. Prisen din blir ikke høyere.', ownedDisclosure: 'Reklame: Denne lenken går til en butikk utgiveren av Husutstyr.no eier selv.', linkLabel: 'Annonselenke', ownedLinkLabel: 'Reklame: Egen butikk' },
  layouts: { home: 'magazine', article: 'editorial' }, minTopicArticles: 5, pageSize: 20,
  fonts: { body: 'Geist', heading: 'Source_Serif_4' },
  media: { sizes: '(max-width: 768px) 100vw, 736px', remotePatterns: [{ protocol: 'https', hostname: '*.public.blob.vercel-storage.com' }] },
  og: { width: 1200, height: 630, padding: 64, titleSize: 64, smallSize: 28 },
  seoTemplates: { home: '{title}', article: '{title}', news: '{title}', review: '{title}', category: '{title}', topic: '{title}', author: '{title}', page: '{title}' },
  labels: { trust: 'Om nettstedet', topics: 'Emner', reviews: 'Anmeldelser', page: 'Side', pagination: 'Flere sider', latest: 'Siste artikler', explore: 'Finn fram etter område', expertise: 'Fagområder', profiles: 'Andre profiler', sources: 'Kilder', method: 'Slik er dette vurdert', rating: 'Vurdering', price: 'Registrert pris', checked: 'Kontrollert', product: 'Produkt', paid: 'Reklame: Det er betalt for denne vurderingen.', owned: 'Reklame: Utgiveren av Husutstyr.no eier dette produktet.', filter: 'Filtrer artikler', sort: 'Rekkefølge', newest: 'Nyeste først', oldest: 'Eldste først', all: 'Alle emner', apply: 'Vis artikler' },
  trustPages: [
    { slug: 'om-oss', title: 'Om oss', todo: 'TODO: Skriv nettstedets historie, reelt eierskap og ansvarlig redaktør.' },
    { slug: 'kontakt', title: 'Kontakt', todo: 'TODO: Oppgi verifisert kontaktinformasjon og hvem som behandler henvendelser.' },
    { slug: 'redaksjonell-policy', title: 'Redaksjonell policy', todo: 'TODO: Beskriv kildekontroll, redigering, rettelser og redaksjonell uavhengighet.' },
    { slug: 'slik-tester-vi', title: 'Slik tester og vurderer vi', todo: 'TODO: Dokumenter egne testmetoder, vurderingskriterier og begrensninger.' },
    { slug: 'personvern', title: 'Personvern', todo: 'TODO: Beskriv reell behandlingsansvarlig, databruk, rettigheter og kontakt.' },
    { slug: 'cookies', title: 'Cookies', todo: 'TODO: Dokumenter faktisk bruk av informasjonskapsler og samtykkevalg.' },
    { slug: 'annonsorinformasjon', title: 'Annonsørinformasjon', todo: 'TODO: Forklar faktiske inntektskilder, kommersielle avtaler og annonsemerking.' },
  ],
  delivery: { robotsDisallow: ['/go/', '/api/', '/redaksjon/'], sitemapMaxUrls: 45000, sitemapMaxBytes: 52428800, indexNowEndpoint: 'https://api.indexnow.org/indexnow', indexNowKeyPath: '/indexnow-key.txt', searchConsole: { status: 'TODO: Verifiser domenet med DNS i Search Console.', checkedAt: null } },
  editorial: {
    issuer: 'https://accounts.google.com', provider: 'Google', priceValidityHours: 24, ratingMin: 1, ratingMax: 5,
    ui: { section: 'Innhold', title: 'Redaksjon', login: 'Logg inn med Google', logout: 'Logg ut', unavailable: 'Innlogging er ikke konfigurert.', forbidden: 'Du har ikke tilgang til denne handlingen.', submitFirst: 'Send revisjonen til vurdering før du godkjenner den.', stale: 'Innholdet er endret siden siden ble lastet. Last inn på nytt og prøv igjen.', unauthenticated: 'Økten er utløpt. Logg inn på nytt.', flowDraft: 'Utkast. Neste steg: send til vurdering.', flowReview: 'Til vurdering. Neste steg: godkjenn revisjonen.', flowApproved: 'Godkjent. Neste steg: publiser revisjonen.', flowPublished: 'Publisert.', invalid: 'Kontroller feltene eller last inn nyeste revisjon.', saved: 'Revisjonen er lagret.', save: 'Lagre nytt utkast', submit: 'Send til vurdering', approve: 'Godkjenn denne revisjonen', create: 'Opprett artikkel', titleField: 'Tittel', summary: 'Ingress', body: 'Brødtekst med tom linje mellom avsnitt', seoTitle: 'Tittel i søkeresultater', description: 'Beskrivelse i søkeresultater', drafts: 'Artikler og revisjoner', preview: 'Privat forhandsvisning', revision: 'Revisjon', state: 'Status', notificationPending: 'Varsling til søketjenesten gjenstår.', notificationRejected: 'Søketjenesten avviste varslingen. Kontroller oppsettet før nytt forsøk.', publish: 'Publiser godkjent revisjon', withdraw: 'Trekk tilbake artikkelen', retry: 'Kontroller publiseringen pa nytt', pending: 'Publiseringen kontrolleres. Last siden pa nytt for status.', confirmed: 'Publiseringen er kontrollert.', superseded: 'Erstattet av en nyere publiseringsjobb.', publishingLater: 'Publisering krever en godkjent revisjon.', empty: 'Ingen artikler tilgjengelig.', category: 'Kategori' },
  },
  home: { title: 'Husutstyr.no – guider og sammenligninger for hele hjemmet', description: 'Vi samler guider, sammenligninger og praktiske råd om utstyr til kjøkken, rengjøring, oppbevaring og vedlikehold, slik at du finner det som passer hjemmet.' },
  id: 'husutstyr',
  identity: { name: 'Husutstyr.no', url: 'https://husutstyr.no' },
  locale: 'nb',
  formattingLocale: 'nb-NO',
  niche: 'hus',
  toneOfVoice: 'Nøktern og konkret bruksveiledning på norsk. Vi beskriver hva utstyret gjør og hvem det passer for, oppgir hva vurderingen bygger på, og unngår superlativer og salgsspråk. Vi er like tydelige på svakheter og på hvem produktet ikke passer for.',
  tokens: {
    '--color-page': '#fdfcfa', '--color-ink': '#1c1a17', '--color-muted': '#5d574e',
    '--color-accent': '#2f5d3f', '--color-surface': '#f4f1ea', '--color-border': '#c2b8a3',
    '--font-body': 'var(--loaded-body), sans-serif', '--font-heading': 'var(--loaded-heading), serif',
    '--text-body': '1rem', '--text-small': '0.875rem', '--text-lead': '1.125rem',
    '--text-heading': '2rem', '--text-subheading': '1.375rem', '--line-body': '1.65', '--line-heading': '1.2',
    '--space-1': '0.25rem', '--space-2': '0.5rem', '--space-3': '0.75rem', '--space-4': '1rem',
    '--space-6': '1.5rem', '--space-8': '2rem', '--space-12': '3rem',
    '--card-min': '18rem', '--sidebar-width': '16rem', '--text-display': '3rem', '--radius': '0', '--shadow': 'none', '--reading-width': '46rem', '--page-width': '68rem',
    '--rule-width': '1px', '--focus-width': '3px', '--weight-heading': '650',
    '--text-minorheading': '1.125rem',
  },
  // Applied under prefers-color-scheme: dark. Every foreground/background pair here clears WCAG AA (>=4.5:1),
  // mirroring the light palette's contrast profile so the same rules hold in both themes.
  tokensDark: {
    '--color-page': '#14130f', '--color-ink': '#eae5d9', '--color-muted': '#a99f8d',
    '--color-accent': '#8cc39b', '--color-surface': '#1f1d16', '--color-border': '#3d382b',
  },
  routes: { reserved: ['anmeldelser', 'api', 'go', 'om-oss', 'kontakt', 'forfatter', 'personvern', 'cookies', 'redaksjon', 'redaksjonell-policy', 'slik-tester-vi', 'annonsorinformasjon', 'emne', 'og', 'visninger', 'sider'], maxSlugLength: 100 },
  ui: { skip: 'Til innholdet', menu: 'Meny', home: 'Forside', category: 'Kategori', read: 'Les artikkelen', contents: 'Til kontrollpunktet', published: 'Publisert', modified: 'Sist oppdatert', author: 'Forfatter', notFound: 'Siden finnes ikke', back: 'Tilbake til forsiden', breadcrumb: 'Brødsmuler' },
  content: { home: 'Guider og sammenligninger av utstyr til hjemmet, fra kjøkken og rengjøring til oppbevaring og vedlikehold.', category: 'Her samler vi guidene, sammenligningene og rådene som hører til dette området.', footer: 'Husutstyr.no. Redaksjonelle vilkår, personvern og annonsørinformasjon finner du i lenkene under.' },
  qa: {
    database: { projectId:'raspy-leaf-06859059', branchId:'br-rough-cake-b22qbr27', branchName:'phase-2-qa', hostPrefix:'ep-plain-forest-b21b1t8k.' },
    phase7: {
      slug: 'qa-phase7-long', title: 'QA: Lang teknisk artikkel med bilder',
      paragraph: 'QA: Syntetisk måleavsnitt for tekstbredde, linjebryting, leserekkefølge og lasting i mobilnett. Teksten er kun teknisk testmateriale og beskriver ingen faktiske produkter, egne tester eller anbefalinger.',
      imageUrl: 'http://127.0.0.1:3104/qa-image.jpg', imageAlt: 'QA: Syntetisk bildeflate for lastetest',
      imageRights: 'QA: Lokalt generert testbilde uten produktpåstander.',
    },
    network: {version:2,sites:[{id:'qa-first',origin:'https://qa-sister-one.invalid',niche:'qa-household',topics:['qa-network-topic']},{id:'qa-second',origin:'https://qa-sister-two.invalid',niche:'qa-household',topics:['qa-network-topic']}]},
    phase6: {
      niche: 'qa-household', origin: 'https://qa-sister-one.invalid', secondOrigin: 'https://qa-sister-two.invalid',
      topic: 'qa-network-topic', topicName: 'QA: Teknisk relevansemne',
      title: 'QA: Kontroll av godkjente nettverkslenker', slug: 'qa-phase6-network',
      firstAnchor: 'QA nettverkskontroll én', secondAnchor: 'QA nettverkskontroll to', thirdAnchor: 'QA nettverkskontroll tre',
      paragraph: 'QA: Denne lokale kontrollteksten inneholder QA nettverkskontroll én, QA nettverkskontroll to og QA nettverkskontroll tre for teknisk verifikasjon. Ingen ekte anbefaling.',
      justification: 'QA: Destinasjonen er registrert med samme tekniske nisje og emne som avsnittet. Dette er en isolert kontroll og ingen redaksjonell anbefaling.',
    },
    phase5: { collectorOrigin: 'http://127.0.0.1:3103', destinationOrigin: 'http://127.0.0.1:3102', destination: 'http://127.0.0.1:3102/produkt?ref=qa-only', link: 'QA: Besøk teknisk testdestinasjon', disclosure: 'QA: Syntetisk provisjonsavtale, ingen faktisk handel.', ownedDisclosure: 'QA: Syntetisk eierskap, ingen faktisk butikk.', title: 'QA: Kontroll av annonselenker og samtykke', slug: 'qa-phase5-affiliate' },
    phase4: {
      title: 'QA: Kontroll av sidetype og publisert navigasjon',
      longTitle: 'QA: Lang publisert tittel for kontroll av delingsbildets linjebryting og hele tekstflaten med norske tegn som kjøkken, rengjøring, oppbevaring og daglige gjøremål i en isolert teknisk kontroll',
      seoTitle: 'Publisert side med teknisk kontrollnummer {id} | QA-mal',
      description: 'Registrert beskrivelse for teknisk kontroll {id} av sidetyper, revisjoner og synlig innhold. Dette er kun lokal QA og ingen reell redaksjonell anbefaling.',
      topicFour: 'QA-emne med fire artikler', topicFive: 'QA-emne med fem artikler',
      product: 'QA-produkt som ikke finnes for salg', manufacturer: 'QA-testdata',
    },
    oidc: { issuer: 'http://127.0.0.1:3101', clientId: 'local-phase-2-qa' },
    markers: { publicationTitle: 'QA: Teknisk publiseringskontroll', publicationBody: 'QA-PUBLISH-001: Teknisk tekst for kontroll av publisert cache.', publicationUpdate: 'QA-PUBLISH-002: Endret teknisk tekst som krever ny godkjenning.', draft: 'QA-PRIVATE-DRAFT-NEVER-PUBLIC', changed: 'QA-CHANGED-REVISION-REQUIRES-APPROVAL', writer: 'qa-writer', editor: 'qa-editor', viewer: 'qa-viewer', outsider: 'qa-unregistered', bio: 'Merket teknisk QA-identitet for lokale integrasjonstester; ikke en ekte forfatter.', expertise: 'Teknisk QA-fixture', research: 'QA-metode: Kontroll av revisjonsbundet dokumentasjon i den isolerte testdatabasen.', evidence: 'Merket QA-dokumentasjon for en teknisk kontroll.', source: 'https://example.com/qa-evidence' },
    identity: { name: 'Husutstyr QA', url: 'http://127.0.0.1:3140' },
    banner: 'LOKAL QA-FIXTURE - Teknisk testinnhold, ikke publisert redaksjonelt innhold.',
    home: {
      title: 'Lokal kontroll av serverrendret innhold | SEO-mal QA',
      description: 'Lokal kvalitetssjekk av malens serverrendring, navigasjon og metadata. Innholdet er en teknisk fixture og skal aldri publiseres som en ekte nettside.',
    },
    category: {
      slug: 'kontroll', name: 'Teknisk kontroll',
      title: 'Artikkelruter og teknisk kategorikontroll | SEO-mal QA',
      description: 'Denne lokale kategorien samler en teknisk testartikkel for kontroll av lenker og metadata. Den er en QA-fixture og skal aldri brukes som ekte innhold.',
    },
    article: {
      id: 'qa-article', slug: 'serverrendret-artikkel', categorySlug: 'kontroll',
      title: 'Kontroll av en serverrendret artikkel',
      summary: 'Teknisk test av HTML, canonical, metadata og strukturert data.',
      body: [
        'QA-BODY-001: Denne teksten skal finnes som synlig artikkelinnhold i den opprinnelige HTML-responsen uten at nettleseren kjorer JavaScript.',
        'QA-BODY-002: Avsnittet er en teknisk kontrollfixture. Det beskriver ingen produkter, tester, priser eller ekte redaksjonelle anbefalinger.',
        'QA-BODY-003: Innholdet er avgrenset til lokal kvalitetssikring. Vanlig produksjonsmodus skal avvise denne artikkelen og alle andre QA-fixtures.',
      ],
      section: { id: 'kontrollpunkt', title: 'Kontrollpunkt for HTML-respons' },
      author: { name: 'QA-testidentitet - ikke en virkelig forfatter', slug: 'qa-testidentitet' },
      publishedAt: '2026-09-07T00:00:00.000Z', modifiedAt: '2026-09-07T00:00:00.000Z',
      seo: {
        title: 'Serverrendret artikkel med kontrollert SEO | SEO-mal QA',
        description: 'Teknisk testartikkel for å kontrollere synlig HTML, en absolutt canonical, unik metadata og gyldig Article-data. Kun en lokal QA-fixture uten publisering.',
      },
    },
  },
} as const satisfies SiteDefinition;

export default site;
