import type { SiteDefinition } from './src/lib/site-types';

const site = {
  network: { version: 1, sites: [] },
  consent: {
    cookieName: 'site_consent', revision: 1, retentionDays: 180,
    ui: {
      settings: 'Personvernvalg', title: 'Ditt valg om analyse',
      description: 'Vi ønsker å bruke Vercel til å måle besøk, teknisk ytelse og klikk på annonselenker. Målingen starter bare hvis du godtar den. Vi husker valget i 180 dager. Du kan endre det via Personvernvalg nederst på siden.',
      accept: 'Godta analyse', reject: 'Avvis analyse', customize: 'Tilpass valg', save: 'Lagre mine valg', close: 'Lukk personvernvalg',
      necessary: 'Nødvendig lagring', necessaryDescription: 'En lokal informasjonskapsel husker valget og versjonen av samtykkepolicyen i 180 dager. Den brukes ikke til analyse eller markedsføring.',
      analytics: 'Besøksanalyse og teknisk ytelse', analyticsDescription: 'Vercel Web Analytics og Speed Insights måler sidebesøk, teknisk ytelse og klikk på annonselenker. Klikkmåling bruker lenke-ID, artikkel-ID, plassering og butikkens domene. Full produktadresse og søkeparametre sendes ikke.',
      revision: 'Samtykkepolicyen er endret. Velg på nytt.', policyLink: '<a href="/personvern">Personvern</a> · <a href="/cookies">Informasjonskapsler</a>',
    },
  },
  measurement: {
    enabled: false,
    analyticsScript: '/_vercel/insights/script.js', analyticsEndpoint: '/_vercel/insights',
    speedScript: '/_vercel/speed-insights/script.js', speedEndpoint: '/_vercel/speed-insights/vitals',
    excludedPaths: ['/api', '/redaksjon', '/go', '/og', '/visninger', '/sider'],
    eventName: 'affiliate_click',
  },
  affiliate: { allowedOrigins: [], disclosure: 'Reklame: Siden inneholder annonselenker. Vi kan motta provisjon når du handler via disse lenkene.', ownedDisclosure: 'Reklame: Siden lenker til en butikk som eies av nettstedets utgiver.', linkLabel: 'Annonselenke', ownedLinkLabel: 'Reklame: Egen butikk' },
  layouts: { home: 'magazine', article: 'editorial' }, minTopicArticles: 5, pageSize: 20,
  fonts: { body: 'Geist', heading: 'Source_Serif_4' },
  media: { sizes: '(max-width: 768px) 100vw, 736px', remotePatterns: [{ protocol: 'https', hostname: '*.public.blob.vercel-storage.com' }] },
  og: { width: 1200, height: 630, padding: 64, titleSize: 64, smallSize: 28 },
  seoTemplates: { home: '{title}', article: '{title}', news: '{title}', review: '{title}', category: '{title}', topic: '{title}', author: '{title}', page: '{title}' },
  labels: { trust: 'Om nettstedet', topics: 'Emner', reviews: 'Anmeldelser', page: 'Side', pagination: 'Flere sider', latest: 'Siste artikler', explore: 'Utforsk kategoriene', expertise: 'Fagområder', profiles: 'Andre profiler', sources: 'Kilder', method: 'Metode og vurdering', rating: 'Vurdering', price: 'Registrert pris', checked: 'Kontrollert', product: 'Produkt', paid: 'Reklame: Vurderingen er betalt.', owned: 'Reklame: Produktet eies av nettstedets utgiver.', filter: 'Filtrer artikler', sort: 'Rekkefølge', newest: 'Nyeste først', oldest: 'Eldste først', all: 'Alle emner', apply: 'Vis artikler' },
  trustPages: [
    { slug: 'om-oss', title: 'Om oss', todo: 'TODO: Skriv nettstedets historie, reelt eierskap og ansvarlig redaktør.' },
    { slug: 'kontakt', title: 'Kontakt', todo: 'TODO: Oppgi verifisert kontaktinformasjon og hvem som behandler henvendelser.' },
    { slug: 'redaksjonell-policy', title: 'Redaksjonell policy', todo: 'TODO: Beskriv kildekontroll, redigering, rettelser og redaksjonell uavhengighet.' },
    { slug: 'slik-tester-vi', title: 'Slik tester og vurderer vi', todo: 'TODO: Dokumenter egne testmetoder, vurderingskriterier og begrensninger.' },
    { slug: 'personvern', title: 'Personvern', todo: 'TODO: Beskriv reell behandlingsansvarlig, databruk, rettigheter og kontakt.' },
    { slug: 'cookies', title: 'Cookies', todo: 'TODO: Dokumenter faktisk bruk av informasjonskapsler og samtykkevalg.' },
    { slug: 'annonsorinformasjon', title: 'Annonsørinformasjon', todo: 'TODO: Forklar faktiske inntektskilder, kommersielle avtaler og annonsemerking.' },
  ],
  delivery: { robotsDisallow: ['/go/', '/api/', '/redaksjon/'], sitemapMaxUrls: 45000, sitemapMaxBytes: 52428800, indexNowEndpoint: 'https://api.indexnow.org/indexnow', indexNowKeyPath: '/indexnow-key.txt', searchConsole: { status: 'TODO: Verifiser domenet med DNS i Search Console.', checkedAt: null } },
  editorial: {
    issuer: 'https://accounts.google.com', provider: 'Google', priceValidityHours: 24, ratingMin: 1, ratingMax: 5,
    ui: { section: 'Innhold', title: 'Redaksjon', login: 'Logg inn med Google', logout: 'Logg ut', unavailable: 'Innlogging er ikke konfigurert.', forbidden: 'Du har ikke tilgang til denne handlingen.', invalid: 'Kontroller feltene eller last inn nyeste revisjon.', saved: 'Revisjonen er lagret.', save: 'Lagre nytt utkast', submit: 'Send til vurdering', approve: 'Godkjenn denne revisjonen', create: 'Opprett artikkel', titleField: 'Tittel', summary: 'Ingress', body: 'Broedtekst med tom linje mellom avsnitt', seoTitle: 'Tittel i soekeresultater', description: 'Beskrivelse i soekeresultater', drafts: 'Artikler og revisjoner', preview: 'Privat forhandsvisning', revision: 'Revisjon', state: 'Status', notificationPending: 'Varsling til soeketjenesten gjenstaar.', notificationRejected: 'Soeketjenesten avviste varslingen. Kontroller oppsettet foer nytt forsoek.', publish: 'Publiser godkjent revisjon', withdraw: 'Trekk tilbake artikkelen', retry: 'Kontroller publiseringen pa nytt', pending: 'Publiseringen kontrolleres. Last siden pa nytt for status.', confirmed: 'Publiseringen er kontrollert.', superseded: 'Erstattet av en nyere publiseringsjobb.', publishingLater: 'Publisering krever en godkjent revisjon.', empty: 'Ingen artikler tilgjengelig.', category: 'Kategori' },
  },
  home: { title: 'Husutstyr – guider og sammenligninger for hele hjemmet', description: 'Vi samler guider, sammenligninger og praktiske råd om utstyr til kjøkken, rengjøring, oppbevaring og vedlikehold, slik at du finner det som passer hjemmet.' },
  id: 'husutstyr',
  identity: { name: 'Husutstyr', url: 'https://husutstyr.no' },
  locale: 'nb',
  formattingLocale: 'nb-NO',
  niche: 'hus',
  toneOfVoice: 'Nøktern og konkret bruksveiledning på norsk. Vi beskriver hva utstyret gjør og hvem det passer for, oppgir hva vurderingen bygger på, og unngår superlativer og salgsspråk.',
  tokens: {
    '--color-page': '#ffffff', '--color-ink': '#182332', '--color-muted': '#495667',
    '--color-accent': '#164ac6', '--color-surface': '#eef3ff', '--color-border': '#c5cedd',
    '--font-body': 'var(--loaded-body), sans-serif', '--font-heading': 'var(--loaded-heading), serif',
    '--text-body': '1rem', '--text-small': '0.875rem', '--text-lead': '1.125rem',
    '--text-heading': '2rem', '--text-subheading': '1.375rem', '--line-body': '1.65', '--line-heading': '1.2',
    '--space-1': '0.25rem', '--space-2': '0.5rem', '--space-3': '0.75rem', '--space-4': '1rem',
    '--space-6': '1.5rem', '--space-8': '2rem', '--space-12': '3rem',
    '--card-min': '18rem', '--sidebar-width': '16rem', '--text-display': '3rem', '--radius': '0.25rem', '--shadow': 'none', '--reading-width': '46rem', '--page-width': '68rem',
    '--rule-width': '1px', '--focus-width': '3px', '--weight-heading': '650',
  },
  routes: { reserved: ['anmeldelser', 'api', 'go', 'om-oss', 'kontakt', 'forfatter', 'personvern', 'cookies', 'redaksjon', 'redaksjonell-policy', 'slik-tester-vi', 'annonsorinformasjon', 'emne', 'og', 'visninger', 'sider'], maxSlugLength: 100 },
  ui: { skip: 'Til innholdet', menu: 'Meny', home: 'Forside', category: 'Kategori', read: 'Les artikkelen', contents: 'Til kontrollpunktet', published: 'Publisert', modified: 'Sist oppdatert', author: 'Forfatter', notFound: 'Siden finnes ikke', back: 'Tilbake til forsiden', breadcrumb: 'Broedsmuler' },
  content: { home: 'Guider og sammenligninger av utstyr til hjemmet, fra kjøkken og rengjøring til oppbevaring og vedlikehold.', category: 'Her samler vi guidene, sammenligningene og rådene som hører til dette området.', footer: 'Husutstyr. Redaksjonelle vilkår, personvern og annonsørinformasjon finner du i lenkene under.' },
  qa: {
    database: { projectId:'raspy-leaf-06859059', branchId:'br-rough-cake-b22qbr27', branchName:'phase-2-qa', hostPrefix:'ep-plain-forest-b21b1t8k.' },
    phase7: {
      slug: 'qa-phase7-long', title: 'QA: Lang teknisk artikkel med bilder',
      paragraph: 'QA: Syntetisk måleavsnitt for tekstbredde, linjebryting, leserekkefølge og lasting i mobilnett. Teksten er kun teknisk testmateriale og beskriver ingen faktiske produkter, egne tester eller anbefalinger.',
      imageUrl: 'http://127.0.0.1:3104/qa-image.jpg', imageAlt: 'QA: Syntetisk bildeflate for lastetest',
      imageRights: 'QA: Lokalt generert testbilde uten produktpåstander.',
    },
    network: {version:2,sites:[{id:'qa-first',origin:'https://qa-sister-one.invalid',niche:'qa-household',topics:['qa-network-topic']},{id:'qa-second',origin:'https://qa-sister-two.invalid',niche:'qa-household',topics:['qa-network-topic']}]},
    phase6: {
      niche: 'qa-household', origin: 'https://qa-sister-one.invalid', secondOrigin: 'https://qa-sister-two.invalid',
      topic: 'qa-network-topic', topicName: 'QA: Teknisk relevansemne',
      title: 'QA: Kontroll av godkjente nettverkslenker', slug: 'qa-phase6-network',
      firstAnchor: 'QA nettverkskontroll én', secondAnchor: 'QA nettverkskontroll to', thirdAnchor: 'QA nettverkskontroll tre',
      paragraph: 'QA: Denne lokale kontrollteksten inneholder QA nettverkskontroll én, QA nettverkskontroll to og QA nettverkskontroll tre for teknisk verifikasjon. Ingen ekte anbefaling.',
      justification: 'QA: Destinasjonen er registrert med samme tekniske nisje og emne som avsnittet. Dette er en isolert kontroll og ingen redaksjonell anbefaling.',
    },
    phase5: { collectorOrigin: 'http://127.0.0.1:3103', destinationOrigin: 'http://127.0.0.1:3102', destination: 'http://127.0.0.1:3102/produkt?ref=qa-only', link: 'QA: Besøk teknisk testdestinasjon', disclosure: 'QA: Syntetisk provisjonsavtale, ingen faktisk handel.', ownedDisclosure: 'QA: Syntetisk eierskap, ingen faktisk butikk.', title: 'QA: Kontroll av annonselenker og samtykke', slug: 'qa-phase5-affiliate' },
    phase4: {
      title: 'QA: Kontroll av sidetype og publisert navigasjon',
      longTitle: 'QA: Lang publisert tittel for kontroll av delingsbildets linjebryting og hele tekstflaten med norske tegn som kjøkken, rengjøring, oppbevaring og daglige gjøremål i en isolert teknisk kontroll',
      seoTitle: 'Publisert side med teknisk kontrollnummer {id} | QA-mal',
      description: 'Registrert beskrivelse for teknisk kontroll {id} av sidetyper, revisjoner og synlig innhold. Dette er kun lokal QA og ingen reell redaksjonell anbefaling.',
      topicFour: 'QA-emne med fire artikler', topicFive: 'QA-emne med fem artikler',
      product: 'QA-produkt som ikke finnes for salg', manufacturer: 'QA-testdata',
    },
    oidc: { issuer: 'http://127.0.0.1:3101', clientId: 'local-phase-2-qa' },
    markers: { publicationTitle: 'QA: Teknisk publiseringskontroll', publicationBody: 'QA-PUBLISH-001: Teknisk tekst for kontroll av publisert cache.', publicationUpdate: 'QA-PUBLISH-002: Endret teknisk tekst som krever ny godkjenning.', draft: 'QA-PRIVATE-DRAFT-NEVER-PUBLIC', changed: 'QA-CHANGED-REVISION-REQUIRES-APPROVAL', writer: 'qa-writer', editor: 'qa-editor', viewer: 'qa-viewer', outsider: 'qa-unregistered', bio: 'Merket teknisk QA-identitet for lokale integrasjonstester; ikke en ekte forfatter.', expertise: 'Teknisk QA-fixture', research: 'QA-metode: Kontroll av revisjonsbundet dokumentasjon i den isolerte testdatabasen.', evidence: 'Merket QA-dokumentasjon for en teknisk kontroll.', source: 'https://example.com/qa-evidence' },
    identity: { name: 'Husutstyr QA', url: 'http://127.0.0.1:3140' },
    banner: 'LOKAL QA-FIXTURE - Teknisk testinnhold, ikke publisert redaksjonelt innhold.',
    home: {
      title: 'Lokal kontroll av serverrendret innhold | SEO-mal QA',
      description: 'Lokal kvalitetssjekk av malens serverrendring, navigasjon og metadata. Innholdet er en teknisk fixture og skal aldri publiseres som en ekte nettside.',
    },
    category: {
      slug: 'kontroll', name: 'Teknisk kontroll',
      title: 'Artikkelruter og teknisk kategorikontroll | SEO-mal QA',
      description: 'Denne lokale kategorien samler en teknisk testartikkel for kontroll av lenker og metadata. Den er en QA-fixture og skal aldri brukes som ekte innhold.',
    },
    article: {
      id: 'qa-article', slug: 'serverrendret-artikkel', categorySlug: 'kontroll',
      title: 'Kontroll av en serverrendret artikkel',
      summary: 'Teknisk test av HTML, canonical, metadata og strukturert data.',
      body: [
        'QA-BODY-001: Denne teksten skal finnes som synlig artikkelinnhold i den opprinnelige HTML-responsen uten at nettleseren kjorer JavaScript.',
        'QA-BODY-002: Avsnittet er en teknisk kontrollfixture. Det beskriver ingen produkter, tester, priser eller ekte redaksjonelle anbefalinger.',
        'QA-BODY-003: Innholdet er avgrenset til lokal kvalitetssikring. Vanlig produksjonsmodus skal avvise denne artikkelen og alle andre QA-fixtures.',
      ],
      section: { id: 'kontrollpunkt', title: 'Kontrollpunkt for HTML-respons' },
      author: { name: 'QA-testidentitet - ikke en virkelig forfatter', slug: 'qa-testidentitet' },
      publishedAt: '2026-09-07T00:00:00.000Z', modifiedAt: '2026-09-07T00:00:00.000Z',
      seo: {
        title: 'Serverrendret artikkel med kontrollert SEO | SEO-mal QA',
        description: 'Teknisk testartikkel for aa kontrollere synlig HTML, en absolutt canonical, unik metadata og gyldig Article-data. Kun en lokal QA-fixture uten publisering.',
      },
    },
  },
} as const satisfies SiteDefinition;

export default site;
