import assert from 'node:assert/strict';
import {spawn} from 'node:child_process';
import {mkdir,writeFile} from 'node:fs/promises';
const env={...process.env,SEO_QA_MODE:'false',OIDC_TEST_MODE:'false',NETWORK_LINKS_ENABLED:'false',VERCEL:'1',VERCEL_ENV:'production',DATABASE_URL_UNPOOLED:''};
const child=spawn('npm',['run','build'],{env,stdio:['ignore','pipe','pipe']});let output='';
child.stdout.on('data',chunk=>{output+=chunk;});child.stderr.on('data',chunk=>{output+=chunk;});
const exitCode=await new Promise((resolve,reject)=>{child.on('error',reject);child.on('close',resolve);});
assert.notEqual(exitCode,0);assert.match(output,/BLOCKED: unfinished-config:identity/);assert.doesNotMatch(output,/Creating an optimized production build/);
await mkdir('docs/qa/phase7',{recursive:true});
await writeFile('docs/qa/phase7/launch-refusal.log',output);
await writeFile('docs/qa/phase7/launch-refusal.json',JSON.stringify({checkedAt:new Date().toISOString(),command:'npm run build',exitCode,status:'PASS',meaning:'The unchanged template refuses a production build before compilation; refusal is expected, not a successful production deployment'},null,2)+'\n');
console.log('PASS: Generic template rejected before production compilation.');
